site_name: WireMock Documentation
site_description: >-
  WireMock Documentation.
# FIXME: replace by production file
site_url: https://wiremock.org
site_2x_url: https://wiremock.org/2.x
copyright: Copyright &copy; 2023 - WireMock Contributors
docs_dir: _site
repo_url: https://github.com/wiremock/wiremock.org
repo_name: WireMock Docs on GitHub
edit_uri: edit/main/_docs/

# Build
site_dir: _site-docs

extra_javascript:
  - js/jquery/jquery=1.12.1.min.js
  - js/faq.js
  - js/codeTab.js
  - js/code-tabs.js
  - js/mobile-navbar.js

# Theme
theme:
  name: material
  custom_dir: _docs_theme
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # NOT compatible qith toc.integrate
    # - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.expand
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: DM Sans
    code: Roboto Mono
  favicon: assets/images/favicon.svg
  logo: images/logos/wiremock/logo_wide.svg
  icon:
    repo: fontawesome/brands/github

extra:
  versions:
    wiremock_version: "3.3.1"
    wiremock_docker_image: "3.3.1-1"
    wiremock_baseline: "3.x"
    grpc_extension_version: 0.4.0
  social:
    - icon: fontawesome/brands/slack
      link: community/slack.md
      name: WireMock Community Slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wiremockorg
      name: WireMock on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wiremock/
      name: WireMock on LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@wiremock
      name: WireMock on Fosstodon
  analytics:
    provider: google
    # FIXME: Update when in Production
    property: G-QSLQ4RWTRP

plugins:
  - extra-sass
  - search
  - autorefs
  - macros
  - render_swagger
  # OpenGraphs
  - social:
      # custom_layouts_dir is commercial feature
  - multirepo:
      # TODO: Change to True once works
      cleanup: false
      keep_docs_dir: false
      nav_repos:
        - name: graphql-extension
          import_url: "https://github.com/wiremock/wiremock-graphql-extension?branch=main&edit_uri=/blob/main/"
          imports: [/README.md, docs/*]
        # - name: grpc-extension
        #   import_url: "https://github.com/wiremock/wiremock-grpc-extension?branch=main&edit_uri=/blob/main/"
        #   imports: [/README.md, docs/*]
        - name: state-extension
          import_url: "https://github.com/wiremock/wiremock-state-extension?branch=develop&edit_uri=/blob/develop/"
          imports: [/README.md, docs/*]
        - name: otel-extension
          import_url: "https://github.com/wiremock/wiremock-otel-extension?branch=main&edit_uri=/blob/main/"
          imports: [/README.md]
        - name: faker-extension
          import_url: "https://github.com/wiremock/wiremock-faker-extension?branch=main&edit_uri=/blob/main/"
          imports: [/README.md]

        # System
        - name: community
          import_url: "https://github.com/wiremock/community?branch=main&edit_uri=/blob/main/"
          imports: ["*"]
        - name: dotgithub
          import_url: "https://github.com/wiremock/.github?branch=main&edit_uri=/blob/main/"
          imports: [CONTRIBUTING.md, SECURITY.md, CODE_OF_CONDUCT.md]
  - redirects:
      redirect_maps:
        "android.md": "solutions/android.md"
        "go.md": "solutions/golang.md"
        "solutions/go.md": "solutions/golang.md"
        "graphql.md": "solutions/graphql.md"
        "testcontainers.md": "solutions/testcontainers.md"
        "spring-boot.md": "solutions/spring-boot.md"
        "api.md": "standalone/admin-api-reference.md"
        "download.md": "download-and-installation.md"
        "tutorials.md": "getting-started.md"
        "plain-java.md": "java-usage.md"
        "junit-rule.md": "junit-extensions.md"
        "junit-4.md": "junit-extensions.md"
        "junit-5.md": "junit-jupiter.md"
        "docker.md": "standalone/docker.md"
        "solutions/docker.md": "standalone/docker.md"
        "running-standalone.md": "standalone/java-jar.md"
        "support.md": "../support"
        "solutions.md": "README.md"

nav:
  - Docs: "!import https://github.com/wiremock/wiremock?branch=docs-experiments&docs_dir=docs&config=mkdocs.yml"

  - Extensions:
      - WireMock Extensions: docs/extensions/README.md
      - gRPC: "!import https://github.com/wiremock/wiremock-grpc-extension?branch=docs-experiments&docs_dir=docs&config=mkdocs.yml"
      - GraphQL: graphql-extension/README.md
      - State: state-extension/README.md
      - Response Template Transformer: docs/response-templating.md
      - Velocity Response Transformer: velocity-transformer-extension/README.md
      - Data Faker: faker-extension/README.md
      - Webhooks: webhooks-and-callbacks.md
      - CORS protection: cors-extension/README.md
      - JSON Web Tokens (JWT): jwt-extension/README.md
      - JSON Body Transformer: 9cookies-extension/json-body-transformer.md
      - Request Time Matcher: 9cookies-extension/request-time-matcher.md
      - Unused Stubs: unused-stubs-extension/README.md
      - Metrics Extension: metrics-extension/README.MD
      - Prometheus Metrics: prometheus-extension/README.md
      - OpenTelemetry: otel-extension/README.md

  - Integrations:
      - WireMock Solution Pages: docs/solutions/README.md
      - Java and JVM Languages: docs/solutions/jvm.md
      - gRPC: docs/grpc.md
      - GraphQL: docs/solutions/graphql.md
      - Python: docs/solutions/python.md
      - Node.js: docs/solutions/nodejs.md
      - .NET: docs/solutions/dotnet.md
      - Golang: docs/solutions/golang.md
      - Rust: docs/solutions/rust.md
      - Kubernetes: docs/solutions/kubernetes.md
      - Testcontainers: docs/solutions/testcontainers.md
      - C/C++: docs/solutions/c_cpp.md

  - Community:
      - Participate in WireMock: docs/participate.md
      - Community Slack: community/slack.md
      - Contributor Guide: community/contributing/README.md
      - Hacktoberfest 2023: dotgithub/CONTRIBUTING.md
      - Creating Extensions: docs/extending-wiremock.md
      - Governance: community/governance/README.md
      - Code of Conduct: dotgithub/CODE_OF_CONDUCT.md

  - Resources:
      - Community Resources: resources/README.md
      - Community Slack: community/slack.md
      - Events:
          Overview: community/events/README.md
          Hacktoberfest: community/events/hacktoberfest/README.md
          Archives: https://www.youtube.com/@WireMockChannel/playlists
          Speaking: community/contributing/README.md#help-to-spread-the-word
      - WireMock Support: dotgithub/SUPPORT.md
      - Reporting Security Issues: dotgithub/SECURITY.md
      - External Resources: resources/external.md

  # Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      title: On this page
      permalink: "#"
